'use client';

import React from 'react';
import { BrainCircuit, TrendingDown, Lightbulb, Zap } from 'lucide-react';
import styles from './insights.module.css';
import Annotation from '../../components/Annotation';

const insights = [
  { 
    id: 1, 
    type: 'bottleneck', 
    title: 'Verification Bottleneck Detected', 
    desc: 'W2 income verifications for Bronze Lite tier are averaging 4.2 days vs 1.1 days baseline. Source identified as API timeout with third-party service.',
    action: 'Switch to secondary provider'
  },
  { 
    id: 2, 
    type: 'optimization', 
    title: 'Workload Imbalance', 
    desc: 'Queue 3 has 45 pending cases while Queue 1 has 2. Automate re-routing to balance case worker load.',
    action: 'Auto-rebalance now'
  },
  { 
    id: 3, 
    type: 'prediction', 
    title: 'Renewal Spike Anticipated', 
    desc: 'Based on historical data and current active cohorts, expect a 210% increase in renewal submissions next Tuesday.',
    action: 'View staffing recommendations'
  }
];

export default function AIInsights() {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>
          <BrainCircuit className={styles.titleIcon} size={28} />
          AI Agent Insights
        </h1>
      </header>

      <div className={styles.gridSystem}>
        <Annotation
          title="Predictive Recommendations"
          what="Actionable suggestions generated by the system's AI analysis."
          why="Reactive management is slow; AI helps supervisors proactively address bottlenecks."
          how="Displaying a categorized list (Bottleneck, Optimization, Prediction) with one-click resolution buttons."
        >
          <div className={styles.card}>
            <div className={styles.cardHeader}>System Recommendations</div>
            <div className={styles.cardContent}>
              <div className={styles.insightList}>
                {insights.map(item => (
                  <div key={item.id} className={styles.insightItem}>
                    <div className={`${styles.insightIcon} ${styles[item.type]}`}>
                      {item.type === 'bottleneck' && <TrendingDown size={20} />}
                      {item.type === 'optimization' && <Zap size={20} />}
                      {item.type === 'prediction' && <Lightbulb size={20} />}
                    </div>
                    <div className={styles.insightBody}>
                      <div className={styles.insightTitle}>{item.title}</div>
                      <div className={styles.insightDesc}>{item.desc}</div>
                      <button className={styles.actionBtn}>{item.action}</button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </Annotation>

        <Annotation
          title="Visual Data Projections"
          what="Charts showing historical data vs AI-predicted trends."
          why="Managers need visual confirmation of 'why' the AI made a recommendation (e.g., seeing the upcoming spike)."
          how="Demonstrating layout structure for charting libraries (like Recharts) integrated cleanly into cards."
        >
          <div className={styles.card}>
            <div className={styles.cardHeader}>7-Day Predictive Volume</div>
            <div className={styles.cardContent}>
              <div className={styles.chartPlaceholder}>
                [ Interactive Chart Rendering Here ]
              </div>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: 1.5 }}>
                The model projects an anomaly in incoming volume starting Monday, likely due to the recent marketing campaign. Ensure at least 5 support personnel are actively monitoring the intake queue.
              </p>
            </div>
          </div>
        </Annotation>
      </div>
    </div>
  );
}
